export const memberJson = [
  {
    "name": "陳柏琳 (Berlin Chen)",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 0,
    "phone": "",
    "email_url": "berlin@csie.ntnu.edu.tw",
    "git_url": "",
    "papers_url": "https://sites.google.com/site/berlinchenatntnu",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/A00_@ntnusmil_berlinchen_profile@_ori.png"
  },
  {
    "name": "林湘婷 (Hsiao-Ting Lin)",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "ntnuedu1822@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "public/images/members/Hsiao-Ting Lin.JPEG"
  },
  {
    "name": "王建鈞",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 1,
    "phone": "",
    "email_url": "jethrowang0531@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "吳映儒",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "innrwu9517@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "鍾念哲",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "markcocowen@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "黃俞華",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "inwater0929@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "何躍陽",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "shawnyang0525@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "黃冠棠",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "i0905108390@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "郭智榮",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "jhih.rong.guo@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "彭安慈",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "anci.peng@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "孫韻婷",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "melodysun90@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "卓妏育",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "nnn7617@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "黃昱綾",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "thalia890824@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "宋宏洋",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "redsheep913@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "劉思廷",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "613k0019c@gapps.ntnu.edu.tw",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "高麒祥",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "gaochisean@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "周星瑀",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "miyukinanako0702@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "曾國瑞",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "60110gary@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "呂益鈞",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "yichunlu707@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "蔡汯劭",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "dhps40303@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "華群宇",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "614k0009c@ntnu.edu.tw",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "郭秉龍",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "a410570231@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "毛煒鈞",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "maowju@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "蔡政翰",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "wow0422796353@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "蔡秉均",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "614k0034c@ntnu.edu.tw",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "顏必成 (Bi-Cheng Yan)",
    "content": "",
    "tags": "1",
    "create_time": "",
    "type": 1,
    "phone": "",
    "email_url": "abc29673260@gmail.com",
    "git_url": "",
    "google_scholar_url": "https://scholar.google.com.tw/citations?user=YVnxMOoAAAAJ&hl=zh-TW",
    "image_url": "https://secure.gravatar.com/avatar/49b44e985c8cb07104e52dbc1f009f768809ff929f3419aa899f40cd1d12dbb9?s=1000&d=retro&r=g"
  },
  {
    "name": "曾厚強 (Ho-Chiang Tseng)",
    "content": "Dissertation: 表徵學習法之文本可讀性 (Representation Learning for Text Readability)",
    "tags": "1",
    "create_time": "",
    "type": 3,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_hctseng-1636356656@_ori.jpg"
  },
  {
    "name": "林士翔 (Shih-Hsiang Lin)",
    "content": "Dissertation: 語音文件摘要 － 特徵、模型與應用 (Speech Summarization - Features, Models and Applications)",
    "tags": "1",
    "create_time": "",
    "type": 3,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_ShihHsiang-1636356656@_ori-1000x1000.jpg"
  },
  {
    "name": "蔡鳳駿 (Fong-Chun Tsai)",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "eoleedimin@gmail.com",
    "git_url": "https://github.com/eoleedi",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/cb272cd3d17d0d46f0d546c65802db42071f9db629d669a2af3229199df55829?s=1000&d=retro&r=g"
  },
  {
    "name": "盧泇良 (Vitas Lu)",
    "content": "",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/5829cd915e9288fa1737486af94924879e2e11f03cad4c75bc048599e101cc7a?s=1000&d=retro&r=g"
  },
  {
    "name": "白立亭 (Li-Ting Pai)",
    "content": "",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/75e44873c139bf022fc662fd2cecc4fd8b73e2e47bdd1aa85b4c9662d27d6075?s=1000&d=retro&r=g"
  },
  {
    "name": "楊承燁 (Jerry Yang)",
    "content": "",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "yang.chan.ya@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/f1c3fab479fd0b03af23a89b1d3d6180e76a913a84df5f74d5c2e06c8835587c?s=1000&d=retro&r=g"
  },
  {
    "name": "方語軒 (Yu-Hsuan Fang)",
    "content": "",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "andy03131121@gmail.com",
    "git_url": "https://github.com/ntnuYuhsuan",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/2025-證件照半身-1000x1000.jpg"
  },
  {
    "name": "吳姿儀 (Tzu-I Wu)",
    "content": "",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/1b1625cae9f4b876e7978c7f1442f74a94769e3fd2298e34de6e0474a5d7de4d?s=1000&d=retro&r=g"
  },
  {
    "name": "林孟欣 (Lin Meng Shin)",
    "content": "",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/35bcf044783f3eaf1d9f468b16917b4892a7edae755c995231b4ab5d6a1fd68b?s=1000&d=retro&r=g"
  },
  {
    "name": "彭玟瑄 (Wen-Hsuan Peng)",
    "content": "",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/3c9425700efb85f4fed99af98ff76438d17f34f03df77c580107bc33166e6519?s=1000&d=retro&r=g"
  },
  {
    "name": "游恩倫 (En-Lun Yu)",
    "content": "",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/af91ec70c8aac52841624848c55c53e87a2a6d281c8d816b83d4e85cedbae1cf?s=1000&d=retro&r=g"
  },
  {
    "name": "楊憶婷 (Yi-Ting Yang)",
    "content": "",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/b51d1f55a1de2aa9e172b37d37c470b36dff5ef1e459355a4f4a61aeba8380b5?s=1000&d=retro&r=g"
  },
  {
    "name": "王泓壬 (Hung-Ren Wang)",
    "content": "",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/38296c3e78be13c8fc6fd8e0d80a63913d2d0c1fffbb268c40476aa387c16fbc?s=1000&d=retro&r=g"
  },
  {
    "name": "何冠勳 (Kuan-Hsun Ho)",
    "content": "",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/3dd2bf9daab7953b27d691d20a303d68e7fffc2e8eb5950cfc0db52f106596b4?s=1000&d=retro&r=g"
  },
  {
    "name": "楊子霆 (Tzu-Ting Yang)",
    "content": "Research Topic: Code Switching on speech recognition",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/ab067d7435c95932bb4a52f86380679f17e59cfa2c438c80d0c43c215ea28769?s=1000&d=retro&r=g"
  },
  {
    "name": "王詣承 (Yi-Cheng Wang)",
    "content": "",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/c7fd056a545fccbfe96c750624ff6744a2b14c444290ee9af87d7ce4cc67bf2f?s=1000&d=retro&r=g"
  },
  {
    "name": "黃怡萍 (Yi-Ping Huang)",
    "content": "",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/f44f9a4765c7cf768333f1cd022742d5854b023973c4fff4139e808b846c256c?s=1000&d=retro&r=g"
  },
  {
    "name": "蔡孟庭 (Meng-Ting Tsai)",
    "content": "",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "mengting7tw@gmail.com",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/IMG_2545-1000x1000.jpg"
  },
  {
    "name": "王馨偉 (HsinWei Wang)",
    "content": "",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/05e76dbf297a2030712e574605bcc336c84a846f3f35c151bff69750afdc5e34?s=1000&d=retro&r=g"
  },
  {
    "name": "李佩穎 (Pei-Ying Lee)",
    "content": "",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/da152740b561da9fbe9b7aab6929d224a101960810dfda34372027444358ecbd?s=1000&d=retro&r=g"
  },
  {
    "name": "吳沁穎 (Chin-Ying Wu)",
    "content": "Thesis: 資訊擷取與知識注入技術於機器閱讀理解之研究 (A Study on Information Extraction and Knowledge Injection for Machine Reading Comprehension)",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/91b5ac583f62bcbf8794ea99776d16f484b4ad69a68afa65e3a2da12579eb5d5?s=1000&d=retro&r=g"
  },
  {
    "name": "謝宛庭 (Wan-Ting Hsieh)",
    "content": "Thesis: 利用多特徵訓練對吉他演奏進行自動採譜 (Automatic Music Transcription of Guitar Performance Using Multitask Learning)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/960d452d40aa27b399707725a46871f46cdbdea93c0bf5f27100ba42ffa36d38?s=1000&d=retro&r=g"
  },
  {
    "name": "曹又升 (Yu-Sheng Tsao)",
    "content": "Thesis: 即時單通道語音增強技術之研究 (A Study on Real-Time Single-Channel Speech Enhancement Techniques)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "https://github.com/samx81",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/355253120_2987717064695889_4539046486831492946_n.jpg"
  },
  {
    "name": "李俊廷 (Jiun-Ting Li)",
    "content": "Thesis: 探討提升自動英語口語評估準確性之方法 - 以會話測試為例 (Exploring Methods to Enhance Accuracy in Automated Speaking Assessment- English Interview as a Case Study)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "https://github.com/a2d8a4v/",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/個人照片1.jpg"
  },
  {
    "name": "施俊良 (Chun-Liang Shih)",
    "content": "",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/949fef0904d1d37fc2f100f82432cba32a706d9cdc9a4ad98aeb98b17e9d0e26?s=1000&d=retro&r=g"
  },
  {
    "name": "鄭宇森 (Yu-Sen Cheng)",
    "content": "Thesis: 語者自動分段標記之改進方法 (Improved Methods for Speaker Diarization)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_DTDwind-1636356657@_ori.jpg"
  },
  {
    "name": "曾琬婷 (Tseng Wen Ting)",
    "content": "Thesis: 結合圖與上下文語言模型技術於常見問答檢索之研究 (A Study on the Combination of Graphs and Contextualized Language Models for FAQ Retrieval)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_Wendy-1636356656@_ori.jpg"
  },
  {
    "name": "范姜紹瑋 (Shao-Wei Fan Jiang)",
    "content": "Thesis: 多編碼器端到端模型於英語錯誤發音檢測與診斷 (Multi-Encoder based End-to-End Model for English Mispronunciation Detection and Diagnosis)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_fanjiang-1636356657@_ori.jpg"
  },
  {
    "name": "邱世弦 (Shih-Hsuan Chiu)",
    "content": "Thesis: 使用跨語句上下文語言模型和圖神經網路於會話語音辨識重新排序之研究 (A Study on Hypothesis Reranking with Cross-utterance Contextualized Language Models and Graph Neural Networks for Conversational Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_60747001S-1636356655@_ori-1000x1000.jpg"
  },
  {
    "name": "趙福安 (Chao Fu An)",
    "content": "Thesis: 結合跨域資訊與時序反轉增強網路於強健性語音辨識 (A Time-reversal Enhancement Network with Cross-domain Information for Noise-robust Automatic Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "https://github.com/fuann",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_60747002S-1636356657@_ori-1000x1000.jpg"
  },
  {
    "name": "林筱芸 (Hsiao-Yun Lin)",
    "content": "Thesis: 探究基於異質圖和上下文語言模型之自動文件摘要技術 (A Study on Heterogeneous Graph Neural Networks and Contextualized Language Models for Text Summarization)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_60747009s-1636356656@_ori.jpg"
  },
  {
    "name": "林韋廷 (Wei-Ting Lin)",
    "content": "Thesis: 探究新穎深度學習方法於中英文混語語音辨識之使用 (Several Novel Deep Learning Approaches to Mandarin-English Code-switching Automatic Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_tinglin-1636356656@_ori-1000x1000.jpg"
  },
  {
    "name": "張修瑞 (Hsiu-Jui Chang)",
    "content": "Thesis: 端對端語音辨識技術於電腦輔助發音訓練 (Computer-assisted Pronunciation Training Leveraging End-to-End Speech Recognition Techniques)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_ft8615236-1636356656@_ori-1000x1000.jpg"
  },
  {
    "name": "劉慈恩 (Tzu-En Liu)",
    "content": "Thesis: 應用階層式語意暨聲學特徵表示於語音文件摘要之研究 (Spoken Document Summarization Leveraging Hierarchical Semantic and Acoustic Representations)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_hane-1636356656@_ori-960x1000.jpg"
  },
  {
    "name": "趙偉成 (Wei-Cheng Chao)",
    "content": "Thesis: 探討預訓練神經網路於語音內涵之機器閱讀理解 (Investigating Pretraining-Based Neural Networks for Machine Comprehension of Spoken Content)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_mitbeaver-1636356657@_ori.jpg"
  },
  {
    "name": "林奕儒 (Yi-Ju Lin)",
    "content": "Thesis: 結合韻律特徵與聲學特徵於錯誤發音檢測與診斷之研究 (Mispronunciation Detection and Diagnosis Combining Prosodic Features and Phonetic Features)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_hhvs1354-1636356657@_ori.jpg"
  },
  {
    "name": "李宗勳 (Tsung-Hsun Lee)",
    "content": "Thesis: 語者確認使用不同語句嵌入函數之比較研究 (A Comparative Study of Utterance-Embedding Generation Functions for Speaker Verification)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/16743cf7ae6633401f9e024ccee57689a64b6cdbcc6ce3b973c17b55a1eb5b94?s=1000&d=retro&r=g"
  },
  {
    "name": "陳映文 (Ying-Wen Chen)",
    "content": "Thesis: 語言模型調適使用語者用詞特徵於會議語音辨識之研究 (Language Model Adaptation Leveraging Speaker-Aware Word-Usage Characteristics for Meeting Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_cliffchen123-1636356656@_ori.jpg"
  },
  {
    "name": "楊明璋 (Ming-Jhang Yang)",
    "content": "Thesis: 探索基於生成對抗網路之新穎強健性技術於語音辨識的應用 (Exploring Generative Adversarial Network Based Robustness Techniques for Automatic Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_mjy-1636356657@_ori-1000x1000.jpg"
  },
  {
    "name": "吳佳樺 (Chia-Hua Wu)",
    "content": "Thesis: 探究有效偵測及修正語音辨識錯誤技術之研究 (A Study on Effective Detection and Correction Techniques for Speech Recognition Errors)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_nemo-1636356655@_ori.jpg"
  },
  {
    "name": "羅天宏 (Tien-Hong Lo)",
    "content": "Thesis: 探討聲學模型化技術與半監督鑑別式訓練於語音辨識之研究 (Investigating Acoustic Modeling and Semi-supervised Discriminative Training for Speech Recognition)",
    "tags": "",
    "create_time": "",
    "type": 1,
    "phone": "",
    "email_url": "teinhonglo@gmail.com",
    "git_url": "https://github.com/teinhonglo",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_teinhonglo-1636356655@_ori-1000x1000.jpg"
  },
  {
    "name": "顏必成 (Bi-Cheng Yan)",
    "content": "Thesis: 探索調變頻譜特徵之低維度結構應用於強健性語音辨識 (Exploring Low-dimensional Structures of Modulation Spectra for Robust Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "abc29673260@gmail.com",
    "git_url": "",
    "google_scholar_url": "https://scholar.google.com.tw/citations?user=YVnxMOoAAAAJ&hl=zh-TW",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_abc29673260-1636356655@_ori.jpg"
  },
  {
    "name": "蔡淳伊 (Chuen-Yi Tsai)",
    "content": "Thesis: 類神經網路技術於自動文件摘要之研究 (A Study on Neural Network Modeling Techniques for Automatic Document Summarization)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_joy36915-1636356656@_ori.jpg"
  },
  {
    "name": "石敬弘 (Chin-Hong Shih)",
    "content": "Thesis: 基於類神經之關聯詞向量表示於文本分類任務之研究 (Neural Relevance-aware Embedding For Text Categorization)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_ntuxd0806-1636356656@_ori.jpg"
  },
  {
    "name": "許曜麒 (Yao-Chi Hsu)",
    "content": "Thesis: 錯誤發音檢測使用評估尺度相關訓練準則 (Mispronunciation Detection with Evaluation Metric-related Training Criteria)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_deer-1636356655@_ori.jpg"
  },
  {
    "name": "楊明翰 (Ming-Han Yang)",
    "content": "Thesis: 改善類神經網路聲學模型經由結合多任務學習與整體學習於會議語音辨識之研究 (Improved Neural Network Based Acoustic Modeling Leveraging Multi-task Learning and Ensemble Learning for Meeting Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_yang-1636356656@_ori.jpg"
  },
  {
    "name": "陳思澄 (Ssu-Cheng Chen)",
    "content": "Thesis: 使用詞向量表示與概念資訊於中文大詞彙連續語音辨識之語言模型調適 (Exploring Word Embedding and Concept Information for Language Model Adaptation in Mandarin Large Vocabulary Continuous Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_boe20211-1636356655@_ori.jpg"
  },
  {
    "name": "施凱文 (Kai-Wun Shih)",
    "content": "Thesis: 表示法學習技術於節錄式語音文件摘要之研究 (A Study on Representation Learning Techniques for Extractive Spoken Document Summarization)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_kevin-1636356655@_ori.jpg"
  },
  {
    "name": "張庭豪 (Ting-Hao Chang)",
    "content": "Thesis: 調變頻譜分解之改良於強健性語音辨識 (Several Refinements of Modulation Spectrum Factorization for Robust Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_qoo55669-1636356657@_ori.jpg"
  },
  {
    "name": "劉憶年 (Yi-Nian Liu)",
    "content": "Thesis: 應用可讀性預測於中小學國語文教科書及優良課外讀物分類之研究 (A Study of Readability Prediction on Elementary and Secondary Chinese Textbook and Excellent Extracurricular Reading Materials Classification)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_ruby-1636356655@_ori.jpg"
  },
  {
    "name": "陳黃威 (Huang-Wei Chen)",
    "content": "Thesis: 改善豐富文脈模型於中文語音合成之研究 (A Study of Enhanced Rich Context Modeling Techniques for Mandarin Speech Synthesis)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_hwchen-1636356655@_ori-1000x1000.jpg"
  },
  {
    "name": "洪孝宗 (Hsiao-Tsung Hung)",
    "content": "Thesis: 聲調特徵擷取技術與其在中文聲調辨識應用之研究 (An Empirical Study on Tonal Feature Extraction Techniques and Their Applications in Mandarin Tone Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_alex-1636356656@_ori.jpg"
  },
  {
    "name": "郝柏翰 (X X)",
    "content": "Thesis: 運用鄰近與概念資訊於語言模型調適之研究 (Leveraging Proximity Cues and Concept Information for Language Model Adaptation in Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_johnhao1206-1636356657@_ori.jpg"
  },
  {
    "name": "汪逸婷 (Yi-Ting Wang)",
    "content": "Thesis: 運用調變頻譜分解技術於強健語音特徵擷取之研究 (Leveraging Modulation Spectrum Factorization Techniques for Robust Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_kame169-1636356656@_ori.jpg"
  },
  {
    "name": "陳俊諭 (X X)",
    "content": "Thesis: 融入文件關聯與查詢清晰度資訊於虛擬關聯回饋之研究 (A Study on Integrating Document Relatedness and Query Clarity Information for Improved Pseudo-Relevance Feedback)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_lettlebread-1636356655@_ori-1000x1000.jpg"
  },
  {
    "name": "高予真 (Yu-Chen Kao)",
    "content": "Thesis: 應用時間結構資訊之分佈式語音特徵參數正規化技術於強健性語音辨識之研究 (Distribution-based Feature Normalization with Temporal-Structural Information on Robust Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_cybeliak-1636356655@_ori.jpg"
  },
  {
    "name": "黃邦烜 (Bang-Hsuan Huang)",
    "content": "Thesis: 遞迴式類神經網路語言模型使用額外資訊於語音辨識之研究 (Recurrent Neural Network-based Language Modeling with Extra Information Cues for Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_doppjk-1636356657@_ori.jpg"
  },
  {
    "name": "張皓欽 (Hao-Chin Chang)",
    "content": "Thesis: 探究語句模型技術應用於摘錄式語音文件摘要 (Sentence Modeling Techniques for Extractive Spoken Document Summarization)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_pizzaboy1029-1636356655@_ori.jpg"
  },
  {
    "name": "陳憶文 (Yi-Wen Chen)",
    "content": "Thesis: 探索虛擬關聯回饋技術和鄰近資訊於語音文件檢索與辨識之改進 (Exploring Effective Pseudo-Relevance Feedback and Proximity Information for Speech Retrieval and Transcription)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_sharre-1636356657@_ori.jpg"
  },
  {
    "name": "朱紋儀 (Wen-Yi Chu)",
    "content": "Thesis: 調變頻譜特徵正規化於強健語音辨識之研究 (Exploring Modulation Spectrum Normalization for Robust Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_Kristy11-1636356656@_ori.jpg"
  },
  {
    "name": "陳珮寧 (Pei-Ning Chen)",
    "content": "Thesis: 查詢模型化於語音文件檢索之研究 (A Study of Query Modeling for Spoken Document Retrieval)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_ning-1636356657@_ori-1000x1000.jpg"
  },
  {
    "name": "賴敏軒 (Min-Hsuan Lai)",
    "content": "Thesis: 實證探究多種鑑別式語言模型於語音辨識之研究 (Empirical Comparisons of Various Discriminative Language Models for Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_tonylai-1636356657@_ori-768x1000.jpg"
  },
  {
    "name": "張鈺玫 (Yu-Mei Chang)",
    "content": "Thesis: 使用多種鑑別式模型以及特徵資訊於語音文件摘要之研究 (Exploiting Various Discriminative Models and Information Cues for Spoken Document Summarization)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_cheese-1636356657@_ori.jpg"
  },
  {
    "name": "劉家妏 (Chia-Wen Liu)",
    "content": "Thesis: 多種鑑別式語言模型應用於語音辨識之研究 (Exploiting Discriminative Language Models for Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_mkacat103-1636356656@_ori.jpg"
  },
  {
    "name": "陳韋豪 (Wen-Hau Chen)",
    "content": "Thesis: 使用空間-時間之特徵分布資訊於強健性語音辨識之研究 (Feature Normalization Exploiting Spatial-Temporal Distribution Characteristics for Robust Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_Howard-1636356656@_ori.jpg"
  },
  {
    "name": "陳冠宇 (Kuan-Yu Chen)",
    "content": "Thesis: 主題模型於語音辨識使用之改進 (Improved Topic Modeling Techniques for Speech Recognition)",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_Menphis-1636356655@_ori.jpg"
  },
  {
    "name": "劉鳳萍 (X X)",
    "content": "Thesis: 使用鑑別式語言模型於語音辨識結果重新排序 (Applying Discriminative Language Models to Reranking of M-best Speech Recognition Results)",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_patty-1636356656@_ori.jpg"
  },
  {
    "name": "羅永典 (Yueng-Tien Lo)",
    "content": "Thesis: 使用邊際資訊於鑑別式聲學模型訓練 (A Study on Margin-Based Discriminative Training of Acoustic Models)",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_ytlo-1636356656@_ori.jpg"
  },
  {
    "name": "游斯涵 (Suhan Yu)",
    "content": "Thesis: 使用機器學習方法於語音文件檢索之研究 (Exploiting Machine Learning Methods for Spoken Document Retrieval)",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_Silvia-1636356657@_ori.jpg"
  },
  {
    "name": "李鴻欣 (Hung-Shin Lee)",
    "content": "Thesis: 基於分類錯誤之線性鑑別式特徵轉換應用於大詞彙連續語音辨識 (Classification Error-based Linear Discriminative Feature Transformation for Large Vocabulary Continuous Speech Recognition)",
    "tags": "",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_Winston-1636356656@_ori.jpg"
  },
  {
    "name": "朱芳輝 (Fang-Hui Chu)",
    "content": "Thesis: 資料選取方法於鑑別式聲學模型訓練之研究 (Training Data Selection for Discriminative Training of Acoustic Models)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_Ryanchu-1636356657@_ori.jpg"
  },
  {
    "name": "許庭瑋 (Ting-Wei Hsu)",
    "content": "Thesis: 英文連續語音辨識之初步研究 (An Initial Study on English Continuous Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_bettyting-1636356656@_ori.jpg"
  },
  {
    "name": "陳鴻彬 (Hung-Bin Chen)",
    "content": "Thesis: 以能量為基礎之語音正規化方法研究及其於語音端點偵測之應用 (On the Study of Energy-Based Speech Feature Normalization and Application to Voice Activity Detection)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_jojo-1636356657@_ori.jpg"
  },
  {
    "name": "林士翔 (Shih-Hsiang Lin)",
    "content": "Thesis: 數據擬合與分群方法於強健語音特徵擷取之研究 (Exploring the Use of Data Fitting and Clustering Techniques for Robust Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://secure.gravatar.com/avatar/46d5c422acbb91af4c9a7aa8138b3853c15cb246ccac7bcfdabb66dc617b2f9d?s=1000&d=retro&r=g"
  },
  {
    "name": "陳怡婷 (Yi-Ting Chen)",
    "content": "Thesis: 中文語音資訊摘要－模型與特徵之改進 (Chinese Speech Information Summarization－Improved Models and Features)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_Felina-1636356655@_ori-1000x1000.jpg"
  },
  {
    "name": "劉士弘 (Shih-Hung Liu)",
    "content": "Thesis: 改善鑑別式聲學模型訓練於中文連續語音辨識之研究 (Improved Discriminative Training of Acoustic Models for Mandarin Continuous Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_bob-1636356655@_ori.jpg"
  },
  {
    "name": "邱炫盛 (Hsuan-Sheng Chiu)",
    "content": "Thesis: 利用主題與位置相關語言模型於中文連續語音辨識 (Exploiting Topic- and Position-Dependent Language Models for Mandarin Continuous Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_mistq-1636356656@_ori.jpg"
  },
  {
    "name": "陳燦輝 (Tzan-Hwei Chen)",
    "content": "Thesis: 信心度評估於中文大詞彙連續語音辨識之研究 (Exploring the Use of Confidence Measures for Mandarin Large Vocabulary Continuous Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_pili-1636356656@_ori.jpg"
  },
  {
    "name": "朱惠銘 (Huei-Ming Chu)",
    "content": "Thesis: 研究使用詞彙與語意資訊於自動語音文件切割與組織應用 (Investigating the Use of Lexical and Semantic Information for Automatic Spoken Document Segmentation and Organization)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_evan-1636356655@_ori.jpg"
  },
  {
    "name": "劉成韋 (Cheng-Wei Liu)",
    "content": "Thesis: 強健性語音辨識上關於特徵正規化與其它改良技術的研究 (A Study on Feature Normalization and Other Improved Techniques for Robust Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_orange-1636356656@_ori.jpg"
  },
  {
    "name": "張志豪 (Chih-Hao Chang)",
    "content": "Thesis: 強健性和鑑別力語音特徵擷取技術於大詞彙連續語音辨識之研究 (Robust And Discriminative Feature Extraction Techniques For Large Vocabulary Continuous Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_topddb-1636356657@_ori.jpg"
  },
  {
    "name": "蔡文鴻 (Wen-Hung Tsai)",
    "content": "Thesis: 語言模型訓練與調適技術於中文大詞彙連續語音辨識之初步研究 (An Initial Study on Language Model Estimation and Adaptation Techniques for Mandarin Large Vocabulary Continuous Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_Louis-1636356656@_ori.jpg"
  },
  {
    "name": "郭人瑋 (Jen-Wei Kuo)",
    "content": "Thesis: 最小化音素錯誤鑑別式聲學模型學習於中文大詞彙連續語音辨識之初步研究 (An Initial Study on Minimum Phone Error Discriminative Learning of Acoustic Models for Mandarin Large Vocabulary Continuous Speech Recognition)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_Roger-1636356657@_ori.jpg"
  },
  {
    "name": "黃耀民 (Yao-Min Huang)",
    "content": "Thesis: 以字句擷取為基礎並應用於文件分類之自動摘要之研究 (Research on Sentence Extraction-based Automatic Summarization Applied to Document Classification)",
    "tags": "1",
    "create_time": "",
    "type": 2,
    "phone": "",
    "email_url": "",
    "git_url": "",
    "google_scholar_url": "",
    "image_url": "https://smil.csie.ntnu.edu.tw/wp-content/uploads/members/A01_@ntnusmil_angus-1636356656@_ori.jpg"
  },
]